# Generated by Django 4.2 on 2026-05-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0002_alter_absence_id_alter_etudiant_id_alter_filiere_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='annee',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='cycle',
            field=models.CharField(choices=[('preparatoire', 'Cycle preparatoire'), ('ingenieur', 'Cycle ingenieur'), ('master', 'Cycle master')], default='preparatoire', max_length=30),
        ),
        migrations.AddField(
            model_name='filiere',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='filiere',
            name='cycle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='filiere',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(default=1)),
                ('niveau', models.CharField(default='1A', max_length=10)),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(max_length=40)),
                ('enseignant', models.CharField(max_length=100)),
                ('type_seance', models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('tp', 'TP'), ('projet', 'Projet'), ('atelier', 'Atelier')], default='cours', max_length=20)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portail.filiere')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portail.module')),
            ],
            options={
                'ordering': ['annee', 'jour', 'heure_debut'],
            },
        ),
    ]
