# Generated by Django 4.2 on 2026-05-01 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0003_etudiant_annee_etudiant_cycle_filiere_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emploidutemps',
            options={'ordering': ['annee', 'groupe__code', 'jour', 'heure_debut']},
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['user__last_name', 'user__first_name', 'matricule']},
        ),
        migrations.AddField(
            model_name='etudiant',
            name='adresse',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='cin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='ville',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('annee', models.PositiveSmallIntegerField(default=1)),
                ('niveau', models.CharField(max_length=10)),
                ('cycle', models.CharField(blank=True, max_length=30)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portail.filiere')),
            ],
            options={
                'ordering': ['annee', 'filiere__code', 'code'],
            },
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portail.groupe'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portail.groupe'),
        ),
    ]
